export const REASSURING_FACTS: string[] = [
  "Tu t'en sors mieux que tu ne le penses.",
  "90% des choses qui nous inquiètent n'arrivent jamais.",
  "Ton cœur a battu des milliards de fois sans que tu n'aies à y penser.",
  "L'anxiété est temporaire. Tu as survécu à 100% de tes pires journées.",
  "Prendre un moment pour respirer n'est jamais du temps perdu.",
  "C'est normal de ne pas aller bien parfois. C'est ça être humain.",
  "Les petits pas en avant restent des progrès.",
  "Tu es plus fort(e) que ce que ton anxiété te dit.",
  "Chaque nouvelle minute est une chance de recommencer à zéro.",
  "Tu n'as pas besoin d'être productif pour avoir de la valeur.",
  "Ton existence est une probabilité d'une sur 400 trillions. Tu es un miracle.",
  "Il y a des gens que tu n'as pas encore rencontrés qui vont t'adorer.",
  "La sensation de panique dure en moyenne moins de 20 minutes.",
  "Tu as le droit de dire non pour protéger ta paix intérieure.",
  "Même les arbres perdent leurs feuilles pour mieux repousser ensuite.",
  "Personne ne sait vraiment ce qu'il fait, on apprend tous en avançant.",
  "Ta valeur ne dépend pas de l'opinion des autres.",
  "Le cerveau a une capacité incroyable à guérir et à s'adapter.",
  "Il est mathématiquement certain que tu as déjà inspiré quelqu'un.",
  "Le monde est plus vaste que tes pensées actuelles.",
  "Il y a une place dans ce monde que seul(e) toi peux occuper.",
  "Ton corps travaille 24h/24 pour te maintenir en vie car il t'aime.",
  "Les erreurs sont les preuves que tu es en train d'essayer.",
  "Tu n'es pas obligé(e) de croire tout ce que ton esprit te dit quand tu es fatigué(e).",
  "La gentillesse que tu donnes finit toujours par te revenir d'une façon ou d'une autre.",
  "Ton passé est un guide, pas une prison.",
  "À cet instant précis, des millions de personnes ressentent la même chose que toi.",
  "Le repos n'est pas une récompense, c'est un besoin fondamental.",
  "Tu as déjà surmonté des choses que tu pensais impossibles autrefois.",
  "Le soleil se lève chaque jour, peu importe à quel point la nuit a été sombre.",
  "La vulnérabilité est une forme de courage, pas de faiblesse.",
  "L'autocompassion est plus efficace que l'autocritique pour progresser.",
  "Chaque respiration est un nouveau départ.",
  "Tu n'as pas besoin d'être parfait(e) pour être aimé(e).",
  "La personne que tu seras dans 5 ans te remercie de ne pas avoir abandonné aujourd'hui.",
];

export const FUN_FACTS: string[] = [
  "Les loutres se tiennent par la main quand elles dorment pour ne pas dériver.",
  "Les manchots font leur demande en mariage avec un caillou.",
  "Les vaches ont des meilleures amies et sont stressées quand elles sont séparées.",
  "Un groupe de flamants roses s'appelle une 'flamboyance'.",
  "Les abeilles peuvent reconnaître les visages humains.",
  "La Norvège a fait chevalier un manchot en 2008.",
  "Les rats et les chiens rigolent quand on les chatouille.",
  "Les écureuils plantent des milliers d'arbres en oubliant leurs cachettes.",
  "Les éléphants pensent que les humains sont 'mignons'.",
  "Les corbeaux se font des cadeaux pour renforcer leurs liens.",
  "Les chats ne miaulent que pour communiquer avec les humains.",
  "Les papillons goûtent avec leurs pattes.",
  "Les wombats font des crottes en forme de cubes.",
  "Une journée sur Vénus est plus longue qu'une année sur Vénus.",
  "Les astronautes grandissent de quelques centimètres dans l'espace.",
  "L'odeur de l'espace ressemble à celle d'un steak grillé ou de métal chaud.",
  "Les pieuvres ont trois cœurs et le sang bleu.",
  "Il pleut des diamants sur Jupiter et Saturne.",
  "Les bananes sont techniquement des baies, mais les fraises ne le sont pas.",
  "Les requins existent depuis plus longtemps que les arbres.",
  "Le miel est le seul aliment qui ne périme jamais.",
  "Il y a plus d'arbres sur Terre que d'étoiles dans la Voie Lactée.",
  "Les hippopotames produisent une sueur rose qui sert de crème solaire.",
  "Les arbres communiquent entre eux via un réseau souterrain de champignons.",
  "Il existe une espèce de méduse qui est biologiquement immortelle.",
  "Les escargots peuvent dormir pendant trois ans.",
  "Les flamants roses sont roses uniquement à cause des crevettes qu'ils mangent.",
  "Le ketchup était vendu comme médicament dans les années 1830.",
  "Ton ADN pourrait s'étirer de la Terre à Pluton et revenir 17 fois.",
  "Les cochons sont incapables de regarder le ciel physiquement.",
];
